# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8f7eb9df650f05c1b13b636fbe9203a2c90b5322b31c621ac4451108ae30162ccf622203b76e69c39729c131be243e7db0d2c17de3ee9ecf10daa0078f67de8

test:
  secret_key_base: 821de9737845814546f24858d34e5febedb63ab29348799f97b1540140637e6aa85b3b08ea35799c14b1d622990eaa3e17f8a90a8f44f5b70eb5e99aabd1e27c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
